// Auto-generated by GrAPP Master Key Generator
const grappSupporters = [
    {
        "name": "BJJ Globetrotters",
        "belt": "red",
        "quote": "",
        "slogan": "Das beste Camp für Grappler aus aller Welt.\nKomm zum nächsten Camp in deiner Nähe!",
        "link": "https://www.bjjglobetrotters.com",
        "logo": "https://picsum.photos/seed/redbelt/400/150" // Placeholder
    },
    {
        "name": "Acai Bros. München",
        "belt": "coral",
        "quote": "",
        "slogan": "",
        "link": "https://instagram.com",
        "logo": "https://picsum.photos/seed/coral/200/100" // Placeholder
    },
    {
        "name": "München Grappling Academy",
        "belt": "coral",
        "quote": "",
        "slogan": "",
        "link": "https://instagram.com",
        "logo": "https://picsum.photos/seed/coral2/200/100" // Placeholder
    },
    {
        "name": "John Danaher",
        "belt": "black",
        "quote": "Why would you ignore 50% of the human body?",
        "slogan": "",
        "link": "https://instagram.com/danaherjohn",
        "logo": ""
    },
    {
        "name": "Max Mustermann",
        "belt": "brown",
        "quote": "Immer auf die Beine!",
        "slogan": "",
        "link": "",
        "logo": ""
    },
    {
        "name": "Sarah Schmidt",
        "belt": "purple",
        "quote": "",
        "slogan": "",
        "link": "",
        "logo": ""
    },
    {
        "name": "Tom Taylor",
        "belt": "blue",
        "quote": "",
        "slogan": "",
        "link": "",
        "logo": ""
    },
    {
        "name": "Kevin Kurz",
        "belt": "white",
        "quote": "",
        "slogan": "",
        "link": "",
        "logo": ""
    }
];
